eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8887
spring:
  application:
    name: spring-dyl-feign
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html