eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8886
spring:
  application:
    name: spring-dyl-client
  data:
    solr:
      host: http://127.0.0.1:8080/solr
  datasource:
    driverclassname: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.200:8066/1804b?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接超时时间（毫秒）
    timeout: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml